// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace PolarkeeperV4.API.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class polarProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(polarProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201505100955119_polarProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
